// Idea inspired by the Pokedex

// My template
//{
//    'Name': '',
//    'Scientific name': '',
//    'Dragon species': '',
//    'Commmon colour(s)': '',
//    'Egg colour(s)': '',
//    'Mass': '',
//    'Size': '',
//    'Lifespan': '',
//   'Special Abilities': '',
//  'Temperament': '',
//  'Social (or solitary)': '',
//  'Preferred environment': '',
//  'Beginner-friendly': '',
//  'Ideal owner': '',
//  'Best suited for': '',
//  'Breeding sanctuary': '',
// },

// Dragon breeds available to purchase (objects)
const breeds = 
[
    {
        'Name': 'Flameheart Drakes',
        'Scientific name': 'Pyrrho Dracius',
        'Dragon species': 'Drakes',
        'Commmon colour(s)': 'Fiery red, orange, and gold',
        'Egg colour(s)': 'Deep crimson with golden speckles',
        'Mass': '300 lbs',
        'Size': 'Medium',
        'Lifespan': '60-80 years',
        'Special Abilities': 'Can breathe controlled flames',
        'Temperament': 'Energetic and curious',
        'Social (or solitary)': 'Social, particularly with other drakes',
        'Preferred environment': 'Volcanic regions and warm habitats',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Adventurous individuals',
        'Best suited for': 'Flying, riding, and elemental displays',
        'Breeding sanctuary': 'Dragagon Drakes',
        'Availability': 'Uncommon',
    },

    {
        'Name': 'Silverscale Drakes',
        'Scientific name': 'Argentdraco Lunaris',
        'Dragon species': 'Drakes',
        'Commmon colour(s)': 'Metallic silvers, grays, and hints of blue',
        'Egg colour(s)': 'Shimmering like moonlit waters',
        'Mass': '350 lbs',
        'Size': 'Medium',
        'Lifespan': '80-100 years',
        'Special Abilities': 'Reflects and amplifies moonlight',
        'Temperament': 'Gentle and intelligent',
        'Social (or solitary)': 'Social, particularly with other drakes',
        'Preferred environment': 'Lakeshores and moonlit landscapes',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Mystics and stargazers',
        'Best suited for': 'Nighttime companionship and moon magic',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Protected',
    },

    {
        'Name': 'Crimsonscale Drakes',
        'Scientific name': 'Pyrrosclera Ignita',
        'Dragon species': 'Drakes',
        'Commmon colour(s)': 'Rich crimsons, deep blacks, and golden accents',
        'Egg colour(s)': 'Glowing with fiery intensity',
        'Mass': '400 lbs',
        'Size': 'Medium',
        'Lifespan': '100-120 years',
        'Special Abilities': 'Breathes searing fire and controls heat',
        'Temperament': 'Assertive and daring',
        'Social (or solitary)': 'Social, particularly with other fire dragons',
        'Preferred environment': 'Volcanic mountains and fiery deserts',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Adventurous warriors and fire elementals',
        'Best suited for': 'Intense combat and heat manipulation',
        'Breeding sanctuary': 'Dragagon Drakes',
        'Availability': 'Common',
    },

    {
        'Name': 'Sapphire Drakes',
        'Scientific name': 'Sapphirdracon Aquarius',
        'Dragon species': 'Drakes',
        'Commmon colour(s)': 'Deep blues, azure hues, and hints of silver',
        'Egg colour(s)': 'Gleaming with sapphire-like luster',
        'Mass': '600 lbs',
        'Size': 'Large',
        'Lifespan': '200-250 years',
        'Special Abilities': 'Enhances water magic and controls currents',
        'Temperament': 'Noble and dignified',
        'Social (or solitary)': 'Social, forms bonds with fellow water dragons',
        'Preferred environment': 'Crystal clear lakes and ocean coasts',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Royalty, diplomats, and water mages',
        'Best suited for': 'Water magic and regal companionship',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Seasonal',
    },

    {
        'Name': 'Jadehide Drakes',
        'Scientific name': 'Viridisclera Natura',
        'Dragon species': 'Drakes',
        'Commmon colour(s)': 'Deep greens, rich emeralds, and verdant browns',
        'Egg colour(s)': 'Adorned with lush foliage patterns',
        'Mass': '350 lbs',
        'Size': 'Medium',
        'Lifespan': '120-150 years',
        'Special Abilities': 'Manipulates plant growth and commands nature',
        'Temperament': 'Tenacious and spirited',
        'Social (or solitary)': 'Social, enjoys the company of creatures',
        'Preferred environment': 'Dense jungles and vibrant meadows',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Jungle adventurers and nature mages',
        'Best suited for': 'Nature magic and jungle exploration',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Common',
    },    

    {
        'Name': 'Rustscale Drakes',
        'Scientific name': 'Ferrascama Robustus',
        'Dragon species': 'Drakes',
        'Commmon colour(s)': 'Earthy browns, rusty reds, and hints of copper',
        'Egg colour(s)': 'Adorned with weathered patterns and colors',
        'Mass': '300 lbs',
        'Size': 'Medium',
        'Lifespan': '120-150 years',
        'Special Abilities': 'Enhances earth magic and controls minerals',
        'Temperament': 'Sturdy and resilient',
        'Social (or solitary)': 'Social, often found in rocky outcrops',
        'Preferred environment': 'Caves and rocky terrain',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Miners, geologists, and earth mages',
        'Best suited for': 'Earth magic and subterranean companionship',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Common',
    },    

    {
        'Name': 'Emberheart Drakes',
        'Scientific name': 'Ignisclera Passionalis',
        'Dragon species': 'Drakes',
        'Commmon colour(s)': 'Deep reds, fiery oranges, and golden accents',
        'Egg colour(s)': 'Gleaming with inner heat and ember-like hues',
        'Mass': '500 lbs',
        'Size': 'Large',
        'Lifespan': '180-220 years',
        'Special Abilities': 'Manipulates flames for combat and warmth',
        'Temperament': 'Passionate and intense',
        'Social (or solitary)': 'Social, often forms close-knit groups',
        'Preferred environment': 'Volcanic regions and fire-laden landscapes',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Warriors, fire mages, and passionate individuals',
        'Best suited for': 'Fire manipulation and strong bonds',
        'Breeding sanctuary': 'Dragagon Drakes',
        'Availability': 'Common',
    },
    
    {
        'Name': 'Amberhide Drakes',
        'Scientific name': 'Amberoscama Durus',
        'Dragon species': 'Drakes',
        'Commmon colour(s)': 'Rich ambers, deep browns, and golden highlights',
        'Egg colour(s)': 'Gleaming with amber-like warmth',
        'Mass': '400 lbs',
        'Size': 'Medium',
        'Lifespan': '150-180 years',
        'Special Abilities': 'Enhances earth magic and controls minerals',
        'Temperament': 'Resilient and enduring',
        'Social (or solitary)': 'Social, often found near ancient trees',
        'Preferred environment': 'Amber-rich caverns and ancient forests',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Explorers, geologists, and earth mages',
        'Best suited for': 'Earth magic and unyielding companionship',
        'Breeding sanctuary': 'Veridinia Hatchery',
        'Availability': 'Common',
    },

    {
        'Name': 'Frostscale Wyverns',
        'Scientific name': 'Glaciescama Wyrmus',
        'Dragon species': 'Wyverns',
        'Commmon colour(s)': 'Icy blues, whites, and pale grays',
        'Egg colour(s)': 'Frosted and shimmering with ice crystals',
        'Mass': '500 lbs',
        'Size': 'Large',
        'Lifespan': '180-220 years',
        'Special Abilities': 'Breathes icy blasts and controls frost',
        'Temperament': 'Cold and aloof, but fiercely protective',
        'Social (or solitary)': 'Solitary, but forms bonds with few',
        'Preferred environment': 'Arctic tundras and snowy peaks',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Skilled ice mages and polar explorers',
        'Best suited for': 'Arctic exploration and defense',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Uncommon',
    },
    
    {
        'Name': 'Aurorafin Wyverns',
        'Scientific name': 'Aurumwing Lumina',
        'Dragon species': 'Wyverns',
        'Commmon colour(s)': 'Radiant golds, yellows, and warm oranges',
        'Egg colour(s)': 'Glowing like the dawning sun',
        'Mass': '300 lbs',
        'Size': 'Medium',
        'Lifespan': '100-120 years',
        'Special Abilities': 'Projects dazzling auroras and light displays',
        'Temperament': 'Playful and energetic',
        'Social (or solitary)': 'Social, often flying in groups',
        'Preferred environment': 'Northern lights regions and alpine meadows',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Performers and sky enthusiasts',
        'Best suited for': 'Aerial shows and companionship',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Rare',
    },
    
    {
        'Name': 'Mystic Wyverns',
        'Scientific name': 'Mysticoscama Divinus',
        'Dragon species': 'Wyverns',
        'Commmon colour(s)': 'Shimmering purples, iridescent blues, and opalescent whites',
        'Egg colour(s)': 'Glowing with inner mystical energy',
        'Mass': '350 lbs',
        'Size': 'Medium',
        'Lifespan': '150-180 years',
        'Special Abilities': 'Manipulates ethereal energies and divination',
        'Temperament': 'Enigmatic and contemplative',
        'Social (or solitary)': 'Solitary, but enjoys thoughtful companionship',
        'Preferred environment': 'Ancient ruins and sacred sites',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Seers, scholars, and mystics',
        'Best suited for': 'Spiritual journeys and divining secrets',
        'Breeding sanctuary': 'Mystique Magesparks',
        'Availability': 'Seasonal',
    },
    
    {
        'Name': 'Galeshadow Wyverns',
        'Scientific name': 'Ventusclera Obscura',
        'Dragon species': 'Wyverns',
        'Commmon colour(s)': 'Dark grays, stormy blues, and deep purples',
        'Egg colour(s)': 'Swirling with dark clouds and winds',
        'Mass': '500 lbs',
        'Size': 'Large',
        'Lifespan': '180-220 years',
        'Special Abilities': 'Commands winds and forms shadowy gusts',
        'Temperament': 'Elusive and elusive',
        'Social (or solitary)': 'Solitary, rarely interacts with others',
        'Preferred environment': 'Cloud-covered mountains and stormy skies',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Sky scouts and air mages',
        'Best suited for': 'Stealthy flight and storm manipulation',
        'Breeding sanctuary': 'Celestria Skyscapes',
        'Availability': 'Uncommon',
    },
    
    {
        'Name': 'Thunderscale Wyverns',
        'Scientific name': 'Fulguraclera Voltus',
        'Dragon species': 'Wyverns',
        'Commmon colour(s)': 'Deep blacks, stormy grays, and lightning-like blues',
        'Egg colour(s)': 'Charged with electricity and vibrating energy',
        'Mass': '500 lbs',
        'Size': 'Large',
        'Lifespan': '180-220 years',
        'Special Abilities': 'Manipulates lightning and charges the air',
        'Temperament': 'Electrifying and dynamic',
        'Social (or solitary)': 'Solitary, prefers to ride the storms alone',
        'Preferred environment': 'Thunderstorms and charged atmospheres',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Storm riders and lightning mages',
        'Best suited for': 'Lightning manipulation and aerial combat',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Seasonal',
    },
    
    {
        'Name': 'Quillfeather Wyverns',
        'Scientific name': 'Foliadraco Curiosa',
        'Dragon species': 'Wyverns',
        'Commmon colour(s)': 'Earthy browns, vibrant greens, and mossy grays',
        'Egg colour(s)': 'Adorned with feather-like patterns and hues',
        'Mass': '300 lbs',
        'Size': 'Medium',
        'Lifespan': '120-150 years',
        'Special Abilities': 'Manipulates plant growth and commands nature',
        'Temperament': 'Curious and playful',
        'Social (or solitary)': 'Social, enjoys company of forest creatures',
        'Preferred environment': 'Enchanted forests and hidden clearings',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Druids, herbalists, and nature lovers',
        'Best suited for': 'Nature magic and forest companionship',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Seasonal',
    },

    {
        'Name': 'Azureglide Wyverns',
        'Scientific name': 'Caeliglide Serenus',
        'Dragon species': 'Wyverns',
        'Commmon colour(s)': 'Sky blues, cloud whites, and airy grays',
        'Egg colour(s)': 'Shimmering like a clear blue sky',
        'Mass': '350 lbs',
        'Size': 'Medium',
        'Lifespan': '120-150 years',
        'Special Abilities': 'Manipulates air currents and glides gracefully',
        'Temperament': 'Gentle and serene',
        'Social (or solitary)': 'Social, often seen in flocks',
        'Preferred environment': 'Open skies and high altitudes',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Pilots, sky travelers, and air mages',
        'Best suited for': 'Aerial displays and sky exploration',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Common',
    },    
    
    {
        'Name': 'Glowstrike Wyverns',
        'Scientific name': 'Lucidoglaucus Radiatus',
        'Dragon species': 'Wyverns',
        'Commmon colour(s)': 'Bioluminescent blues, greens, and iridescent purples',
        'Egg colour(s)': 'Glowing with inner radiance and soft light',
        'Mass': '400 lbs',
        'Size': 'Medium',
        'Lifespan': '150-180 years',
        'Special Abilities': 'Creates dazzling displays of light and color',
        'Temperament': 'Luminescent and vibrant',
        'Social (or solitary)': 'Social, often congregates in caverns',
        'Preferred environment': 'Caverns and underground crystal formations',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Gemologists, explorers, and light mages',
        'Best suited for': 'Light magic and subterranean exploration',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Uncommon',
    },
    
    {
        'Name': 'Cobalt Wyverns',
        'Scientific name': 'Caeruleaglide Glacialis',
        'Dragon species': 'Wyverns',
        'Commmon colour(s)': 'Deep blues, icy grays, and hints of silver',
        'Egg colour(s)': 'Gleaming like polished sapphire',
        'Mass': '400 lbs',
        'Size': 'Medium',
        'Lifespan': '150-180 years',
        'Special Abilities': 'Controls ice and frost, glides with grace',
        'Temperament': 'Agile and dynamic',
        'Social (or solitary)': 'Social, often seen in pairs',
        'Preferred environment': 'Arctic cliffs and icy landscapes',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Arctic explorers and ice mages',
        'Best suited for': 'Ice manipulation and aerial agility',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Seasonal',
    },
    
    {
        'Name': 'Cerulean Wyverns',
        'Scientific name': 'Caeruleusglide Serenus',
        'Dragon species': 'Wyverns',
        'Commmon colour(s)': 'Ocean blues, pale grays, and azure accents',
        'Egg colour(s)': 'Shimmering like tranquil ocean waters',
        'Mass': '300 lbs',
        'Size': 'Medium',
        'Lifespan': '100-120 years',
        'Special Abilities': 'Controls water currents and calm seas',
        'Temperament': 'Serene and calming',
        'Social (or solitary)': 'Social, often seen near the shore',
        'Preferred environment': 'Coastal shores and serene bays',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Beachcombers and ocean lovers',
        'Best suited for': 'Water manipulation and oceanic exploration',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Common',
    },
    
    {
        'Name': 'Obsidian Wyverns',
        'Scientific name': 'Obsidianoglaucus Obscurus',
        'Dragon species': 'Wyverns',
        'Commmon colour(s)': 'Dark blacks, deep grays, and iridescent hints',
        'Egg colour(s)': 'Gleaming like polished obsidian',
        'Mass': '500 lbs',
        'Size': 'Large',
        'Lifespan': '200-250 years',
        'Special Abilities': 'Manipulates shadows and commands darkness',
        'Temperament': 'Intense and mysterious',
        'Social (or solitary)': 'Solitary, preferring the company of shadows',
        'Preferred environment': 'Moonless nights and shadowy realms',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Nightmares, shadowmancers, and enigmatic souls',
        'Best suited for': 'Shadow manipulation and night flights',
        'Breeding sanctuary': 'Dregicess Enclaves',
        'Availability': 'Rare',
    },
    
    {
        'Name': 'Mistral Wyverns',
        'Scientific name': 'Zephyroglide Serenus',
        'Dragon species': 'Wyverns',
        'Commmon colour(s)': 'Soft grays, sky blues, and airy whites',
        'Egg colour(s)': 'Swirling with mist and gentle breezes',
        'Mass': '350 lbs',
        'Size': 'Medium',
        'Lifespan': '120-150 years',
        'Special Abilities': 'Manipulates gentle winds and controls mist',
        'Temperament': 'Calm and tranquil',
        'Social (or solitary)': 'Social, often seen gliding together',
        'Preferred environment': 'High altitudes and mist-covered valleys',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Meditators, aerial artists, and wind mages',
        'Best suited for': 'Aerial meditation and calming presence',
        'Breeding sanctuary': 'Celestria Skyscapes',
        'Availability': 'Common',
    },
    
    {
        'Name': 'Runic Wyverns',
        'Scientific name': 'Runeglidus Arcanum',
        'Dragon species': 'Wyverns',
        'Commmon colour(s)': 'Mysterious blacks, ancient grays, and glowing runes',
        'Egg colour(s)': 'Adorned with intricate rune-like patterns',
        'Mass': '400 lbs',
        'Size': 'Medium',
        'Lifespan': '180-220 years',
        'Special Abilities': 'Manipulates runic magic and ancient knowledge',
        'Temperament': 'Enigmatic and thoughtful',
        'Social (or solitary)': 'Solitary, often seeking solitude for study',
        'Preferred environment': 'Ancient ruins and arcane libraries',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Sages, scholars, and magic historians',
        'Best suited for': 'Runic magic and deciphering mysteries',
        'Breeding sanctuary': 'Mystique Magesparks',
        'Availability': 'Seasonal',
    },
    
    {
        'Name': 'Petalflare Wyverns',
        'Scientific name': 'Flammapetala Ignis',
        'Dragon species': 'Wyverns',
        'Commmon colour(s)': 'Radiant oranges, fiery reds, and hints of gold',
        'Egg colour(s)': 'Gleaming with vibrant floral patterns',
        'Mass': '450 lbs',
        'Size': 'Medium',
        'Lifespan': '180-220 years',
        'Special Abilities': 'Manipulates fire and commands flower growth',
        'Temperament': 'Fiery and passionate',
        'Social (or solitary)': 'Solitary, prefers open landscapes',
        'Preferred environment': 'Wildflower fields and volcanic landscapes',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Fire mages, volcano enthusiasts, and passionate souls',
        'Best suited for': "Fire magic and embracing nature's fury",
        'Breeding sanctuary': 'Veridinia Hatchery',
        'Availability': 'Seasonal',
    },
    
    {
        'Name': 'Crystalwing Dragons',
        'Scientific name': 'Cristalithes Lucidus',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Iridescent blues, greens, and purples',
        'Egg colour(s)': 'Translucent with swirling colors',
        'Mass': '180 lbs',
        'Size': 'Small to medium',
        'Lifespan': '120-150 years',
        'Special Abilities': 'Can refract light and create illusions',
        'Temperament': 'Gentle and intelligent',
        'Social (or solitary)': 'Social, especially within their kind',
        'Preferred environment': 'Forested areas and clearings',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Artistic and imaginative individuals',
        'Best suited for': 'Magic-oriented companionship, flying',
        'Breeding sanctuary': 'Deainuis Dragonry',
        'Availability': 'Limited',
    },
    
    {
        'Name': 'Shadowcoil Dragons',
        'Scientific name': 'Umbradracon Coilus',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Deep purples, blacks, and indigo',
        'Egg colour(s)': 'Dark with faint bioluminescent patterns',
        'Mass': '600 lbs',
        'Size': 'Large',
        'Lifespan': '200-250 years',
        'Special Abilities': 'Can manipulate shadows and darkness',
        'Temperament': 'Mysterious and reserved',
        'Social (or solitary)': 'Solitary, but may form bonds with owners',
        'Preferred environment': 'Caves, moonlit areas',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Skilled sorcerers and shadow manipulators',
        'Best suited for': 'Stealth and magical combat',
        'Breeding sanctuary': 'Dregicess Enclaves',
        'Availability': 'Seasonal',
    },
    
    {
        'Name': 'Dawnstrike Dragons',
        'Scientific name': 'Auroradracon Luminus',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Soft pinks, golds, and pastels',
        'Egg colour(s)': 'Radiant with warm, sunrise-like hues',
        'Mass': '250 lbs',
        'Size': 'Medium',
        'Lifespan': '100-120 years',
        'Special Abilities': 'Can create dazzling light displays',
        'Temperament': 'Playful and affectionate',
        'Social (or solitary)': 'Social, forming close bonds with owners',
        'Preferred environment': 'Open meadows and hills',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Families and individuals seeking loyal companions',
        'Best suited for': 'Companionship, flying, and light-based magic',
        'Breeding sanctuary': 'Auroradawn Keep',
        'Availability': 'Common',
    },
    
    {
        'Name': 'Eclipseclaw Dragons',
        'Scientific name': 'Noctisclaw Obscurus',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Dark purples, blues, and silvers',
        'Egg colour(s)': 'Shrouded in swirling shadows',
        'Mass': '450 lbs',
        'Size': 'Medium to large',
        'Lifespan': '180-220 years',
        'Special Abilities': 'Manipulates darkness and lunar energy',
        'Temperament': 'Mysterious and enigmatic',
        'Social (or solitary)': 'Solitary, forming connections with few',
        'Preferred environment': 'Moonlit forests and hidden caves',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Skilled shadowmancers and moonlight seekers',
        'Best suited for': 'Stealthy magical warfare and night flying',
        'Breeding sanctuary': 'Solstice Sanctums',
        'Availability': 'Common',
    },
    
    {
        'Name': 'Stormwing Dragons',
        'Scientific name': 'Fulgrodracon Tempestus',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Thunderous grays, dark blues, and electric purples',
        'Egg colour(s)': 'Sparking with electricity and swirling clouds',
        'Mass': '600 lbs',
        'Size': 'Large',
        'Lifespan': '200-250 years',
        'Special Abilities': 'Manipulates lightning and weather patterns',
        'Temperament': 'Fierce and unpredictable',
        'Social (or solitary)': 'Solitary, prefers isolation during storms',
        'Preferred environment': 'Stormy skies and lightning-rich areas',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Bold storm chasers and weather mages',
        'Best suited for': 'Storm manipulation and aerial combat',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Common',
    },
    
    {
        'Name': 'Emberclaw Dragons',
        'Scientific name': 'Ignisclaw Infernus',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Fiery reds, deep blacks, and ember-like oranges',
        'Egg colour(s)': 'Gleaming with inner heat and sparks',
        'Mass': '500 lbs',
        'Size': 'Large',
        'Lifespan': '180-220 years',
        'Special Abilities': 'Manipulates flames for combat and forging',
        'Temperament': 'Passionate and fierce',
        'Social (or solitary)': 'Social, forms bonds with fellow fire dragons',
        'Preferred environment': 'Volcanic calderas and fire-laden landscapes',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Blacksmiths, warriors, and fire mages',
        'Best suited for': 'Fire magic and forging partnerships',
        'Breeding sanctuary': 'Dragagon Drakes',
        'Availability': 'Seasonal',
    },
    
    {
        'Name': 'Opalescent Dragons',
        'Scientific name': 'Iridescendis Magica',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Pearlescent whites, pastel hues, and shifting rainbows',
        'Egg colour(s)': 'Reflective and ever-changing colors',
        'Mass': '300 lbs',
        'Size': 'Medium',
        'Lifespan': '120-150 years',
        'Special Abilities': 'Creates illusions and light-based magic',
        'Temperament': 'Playful and mischievous',
        'Social (or solitary)': 'Social, enjoys playful interactions',
        'Preferred environment': 'Crystal caves and prismatic landscapes',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Tricksters, illusionists, and artists',
        'Best suited for': 'Illusion magic and prismatic displays',
        'Breeding sanctuary': 'Deainuis Dragonry',
        'Availability': 'Limited',
    },
    
    {
        'Name': 'Topazscale Dragons',
        'Scientific name': 'Aurumscama Radiatus',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Vibrant yellows, deep golds, and warm oranges',
        'Egg colour(s)': 'Gleaming with inner radiance',
        'Mass': '350 lbs',
        'Size': 'Medium',
        'Lifespan': '80-100 years',
        'Special Abilities': 'Enhances light magic and radiates warmth',
        'Temperament': 'Lively and energetic',
        'Social (or solitary)': 'Social, often basking in groups',
        'Preferred environment': 'Sunlit valleys and golden meadows',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Nature enthusiasts and light mages',
        'Best suited for': 'Light magic and sunlit companionship',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Rare',
    },
    
    {
        'Name': 'Gloomwing Dragons',
        'Scientific name': 'Nocturnisclera Astralis',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Dark blues, smoky grays, and muted purples',
        'Egg colour(s)': 'Veiled in shadows and faint starlight',
        'Mass': '400 lbs',
        'Size': 'Medium',
        'Lifespan': '150-180 years',
        'Special Abilities': 'Manipulates darkness and astral energy',
        'Temperament': 'Melancholic and introspective',
        'Social (or solitary)': 'Solitary, seeks quiet reflection',
        'Preferred environment': 'Twilight forests and moonlit groves',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Astral travelers and night mages',
        'Best suited for': 'Shadow manipulation and starlit magic',
        'Breeding sanctuary': 'Mystique Magesparks',
        'Availability': 'Rare',
    },
    
    {
        'Name': 'Ivoryscale Dragons',
        'Scientific name': 'Albidracon Serenitas',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Creamy whites, soft golds, and delicate pastels',
        'Egg colour(s)': 'Luminescent and reminiscent of moonlit seashores',
        'Mass': '300 lbs',
        'Size': 'Medium',
        'Lifespan': '120-150 years',
        'Special Abilities': 'Enhances light magic and radiates calm',
        'Temperament': 'Graceful and serene',
        'Social (or solitary)': 'Social, enjoys peaceful gatherings',
        'Preferred environment': 'Coastal cliffs and moonlit beaches',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Healers, artists, and those seeking peace',
        'Best suited for': 'Healing magic and tranquil companionship',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Seasonal',
    },
    
    {
        'Name': 'Echowave Dragons',
        'Scientific name': 'Sonodracon Maris',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Ocean blues, aquamarines, and shimmering silvers',
        'Egg colour(s)': 'Rippling with waves and aquatic energy',
        'Mass': '350 lbs',
        'Size': 'Medium',
        'Lifespan': '150-180 years',
        'Special Abilities': 'Communicates through sound and water magic',
        'Temperament': 'Harmonious and intuitive',
        'Social (or solitary)': 'Social, forms connections with ocean life',
        'Preferred environment': 'Coastal waters and coral reefs',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Oceanographers and healers',
        'Best suited for': 'Aquatic magic and empathetic companionship',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Uncommon',
    },
    
    {
        'Name': 'Glimmerwing Dragons',
        'Scientific name': 'Iridescendis Arcana',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Iridescent purples, deep blues, and shimmering silvers',
        'Egg colour(s)': 'Glowing with internal luminescence',
        'Mass': '400 lbs',
        'Size': 'Medium',
        'Lifespan': '180-220 years',
        'Special Abilities': 'Manipulates illusion magic and reflects light',
        'Temperament': 'Mystical and enigmatic',
        'Social (or solitary)': 'Solitary, seeks to unravel mysteries',
        'Preferred environment': 'Moonlit groves and enchanted glades',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Enchanters, astrologers, and dreamwalkers',
        'Best suited for': 'Illusion magic and moonlit companionship',
        'Breeding sanctuary': 'Mystique Magesparks',
        'Availability': 'Uncommon',
    },
    
    {
        'Name': 'Sandflare Dragons',
        'Scientific name': 'Arenascama Solis',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Desert yellows, warm oranges, and sunlit golds',
        'Egg colour(s)': 'Gleaming with desert sands and solar energy',
        'Mass': '300 lbs',
        'Size': 'Medium',
        'Lifespan': '100-120 years',
        'Special Abilities': 'Manipulates desert sand and heat',
        'Temperament': 'Resilient and adaptable',
        'Social (or solitary)': 'Social, forms bonds with desert creatures',
        'Preferred environment': 'Arid deserts and sun-soaked dunes',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Nomads, desert explorers, and sun mages',
        'Best suited for': 'Desert survival and solar magic',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Common',
    },
    
    {
        'Name': 'Eldertide Dragons',
        'Scientific name': 'Sylvadracon Antiquus',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Ancient greens, deep blues, and silver accents',
        'Egg colour(s)': 'Adorned with intricate patterns reminiscent of old forests',
        'Mass': '600 lbs',
        'Size': 'Large',
        'Lifespan': '300-350 years',
        'Special Abilities': 'Commands plant life and ancient magic',
        'Temperament': 'Wise and venerable',
        'Social (or solitary)': 'Solitary, but appreciates wisdom seekers',
        'Preferred environment': 'Ancient forests and mystical groves',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Druids, scholars, and history enthusiasts',
        'Best suited for': 'Earth magic and ancient wisdom',
        'Breeding sanctuary': 'Veridinia Hatchery',
        'Availability': 'Rare',
    },
    
    {
        'Name': 'Ironscale Dragons',
        'Scientific name': 'Ferrumscama Fortis',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Metallic grays, sturdy blacks, and hints of bronze',
        'Egg colour(s)': 'Gleaming like polished metal',
        'Mass': '700 lbs',
        'Size': 'Large',
        'Lifespan': '250-300 years',
        'Special Abilities': 'Manipulates metal and fortifies defenses',
        'Temperament': 'Resilient and unyielding',
        'Social (or solitary)': 'Solitary, prefers solitude in the mountains',
        'Preferred environment': 'Mountainous regions and ore-rich caverns',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Blacksmiths, engineers, and metal mages',
        'Best suited for': 'Metalworking and defensive magic',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Common',
    },
    
    {
        'Name': 'Sunflare Dragons',
        'Scientific name': 'Solscama Brillans',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Radiant golds, fiery oranges, and sunny yellows',
        'Egg colour(s)': 'Gleaming with solar brilliance',
        'Mass': '300 lbs',
        'Size': 'Medium',
        'Lifespan': '100-120 years',
        'Special Abilities': 'Channels solar energy and radiates warmth',
        'Temperament': 'Bright and enthusiastic',
        'Social (or solitary)': 'Social, enjoys sunlit gatherings',
        'Preferred environment': 'Sun-soaked meadows and desert oases',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Sun worshippers, sun mages, and joyful souls',
        'Best suited for': 'Solar magic and sunny companionship',
        'Breeding sanctuary': 'Auroradawn Keep',
        'Availability': 'Common',
    },
    
    {
        'Name': 'Frostveil Dragons',
        'Scientific name': 'Glaciescama Serenitas',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Icy blues, frosty whites, and silver accents',
        'Egg colour(s)': 'Gleaming with frost and icy patterns',
        'Mass': '400 lbs',
        'Size': 'Medium',
        'Lifespan': '150-180 years',
        'Special Abilities': 'Manipulates cold and controls frost',
        'Temperament': 'Chill and composed',
        'Social (or solitary)': 'Social, forms bonds with fellow ice dragons',
        'Preferred environment': 'Snow-covered mountains and frozen landscapes',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Ice mages, mountaineers, and contemplative souls',
        'Best suited for': 'Ice magic and serene companionship',
        'Breeding sanctuary': 'Solstice Sanctums',
        'Availability': 'Seasonal',
    },
    
    {
        'Name': 'Verdelight Dragons',
        'Scientific name': 'Viridisclera Lucida',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Rich greens, vibrant emeralds, and gold accents',
        'Egg colour(s)': 'Glowing with lush vitality',
        'Mass': '350 lbs',
        'Size': 'Medium',
        'Lifespan': '120-150 years',
        'Special Abilities': 'Enhances plant growth and radiates energy',
        'Temperament': 'Lively and exuberant',
        'Social (or solitary)': 'Social, often found in verdant environments',
        'Preferred environment': 'Vibrant gardens and enchanted forests',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Gardeners, plant mages, and nature enthusiasts',
        'Best suited for': 'Plant magic and joyous companionship',
        'Breeding sanctuary': 'Veridinia Hatchery',
        'Availability': 'Common',
    },
    
    {
        'Name': 'Celestial Dragons',
        'Scientific name': 'Astraeodracon Ethereus',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Cosmic blues, starlit silvers, and radiant golds',
        'Egg colour(s)': 'Gleaming with celestial energy and stardust',
        'Mass': '600 lbs',
        'Size': 'Large',
        'Lifespan': '300-350 years',
        'Special Abilities': 'Manipulates cosmic energies and starlight',
        'Temperament': 'Ethereal and transcendent',
        'Social (or solitary)': 'Solitary, often meditating among the stars',
        'Preferred environment': 'Astral planes and star-filled skies',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Astrologers, cosmic mages, and seekers of wisdom',
        'Best suited for': 'Celestial magic and cosmic contemplation',
        'Breeding sanctuary': 'Mystique Magesparks',
        'Availability': 'Limited',
    },
    
    {
        'Name': 'Blossomwing Dragons',
        'Scientific name': 'Florascala Serenitas',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Soft pinks, delicate purples, and petal-like patterns',
        'Egg colour(s)': 'Adorned with floral motifs and pastel hues',
        'Mass': '300 lbs',
        'Size': 'Medium',
        'Lifespan': '120-150 years',
        'Special Abilities': 'Enhances nature magic and communicates with plants',
        'Temperament': 'Gentle and nurturing',
        'Social (or solitary)': 'Social, often seen among blooming flora',
        'Preferred environment': 'Flower-filled meadows and lush gardens',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Herbalists, gardeners, and nature-loving souls',
        'Best suited for': 'Floral magic and cultivating harmony',
        'Breeding sanctuary': 'Veridinia Hatchery',
        'Availability': 'Common',
    },
    
    {
        'Name': 'Aurorafin Dragons',
        'Scientific name': 'Solisaurum Brillans',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Shimmering golds, radiant yellows, and solar accents',
        'Egg colour(s)': 'Gleaming like the rising sun',
        'Mass': '350 lbs',
        'Size': 'Medium',
        'Lifespan': '100-120 years',
        'Special Abilities': 'Channels solar energy and shines brightly',
        'Temperament': 'Luminous and radiant',
        'Social (or solitary)': 'Social, often seen greeting the sunrise',
        'Preferred environment': 'Dawn-lit valleys and mountain peaks',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Early risers, sun mages, and light-hearted souls',
        'Best suited for': 'Solar magic and dawn companionship',
        'Breeding sanctuary': 'Veridinia Hatchery',
        'Availability': 'Uncommon',
    },
    
    {
        'Name': 'Verdeflame Dragons',
        'Scientific name': 'Virideflamma Vitalis',
        'Dragon species': 'Dragons',
        'Commmon colour(s)': 'Verdant greens, fiery oranges, and hints of gold',
        'Egg colour(s)': 'Glowing with the melding of fire and foliage',
        'Mass': '400 lbs',
        'Size': 'Medium',
        'Lifespan': '150-180 years',
        'Special Abilities': 'Enhances fire and plant magic, embodies growth',
        'Temperament': 'Energetic and vibrant',
        'Social (or solitary)': 'Social, often seen among lush landscapes',
        'Preferred environment': 'Enchanted forests and volcanic clearings',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Elementalists, naturalists, and those seeking balance',
        'Best suited for': 'Elemental fusion and harmonizing opposites',
        'Breeding sanctuary': 'Veridinia Hatchery',
        'Availability': 'Seasonal',
    },
    
    {
        'Name': 'Shadowfire Wyrms',
        'Scientific name': 'Igniscauda Obscuratus',
        'Dragon species': 'Wyrms',
        'Commmon colour(s)': 'Smoky blacks, purples, and embers of red',
        'Egg colour(s)': 'Glowing with inner magical fire',
        'Mass': '1500 lbs',
        'Size': 'Massive',
        'Lifespan': '500-600 years',
        'Special Abilities': 'Wields potent dark and fire magic',
        'Temperament': 'Ancient and wise',
        'Social (or solitary)': 'Solitary, with strong bonds to magical practitioners',
        'Preferred environment': 'Caverns and underground labyrinths',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Accomplished sorcerers and scholars of ancient lore',
        'Best suited for': 'Ancient magic and guardianship',
        'Breeding sanctuary': 'Mystique Magesparks',
        'Availability': 'Rare',
    },
    
    {
        'Name': 'Mistveil Wyrms',
        'Scientific name': 'Nebuladraco Serenus',
        'Dragon species': 'Wyrms',
        'Commmon colour(s)': 'Ethereal whites, pale blues, and misty grays',
        'Egg colour(s)': 'Shrouded in mist and faint moonlight',
        'Mass': '800 lbs',
        'Size': 'Large',
        'Lifespan': '250-300 years',
        'Special Abilities': 'Manipulates fog and controls water magic',
        'Temperament': 'Serene and calming',
        'Social (or solitary)': 'Solitary, but enjoys gentle interactions',
        'Preferred environment': 'Enchanted lakes and misty swamps',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Water mages and those seeking tranquility',
        'Best suited for': 'Water magic and peaceful companionship',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Seasonal',
    },
    
    {
        'Name': 'Lavabane Wyrms',
        'Common Colors': 'Fiery reds, molten oranges, and smoldering blacks',
        'Egg Colors': 'Glowing with internal lava-like heat',
        'Temperament': 'Intense and fiery',
        'Beginner Friendly': 'No',
        'Size': 'Large',
        'Special Abilities': 'Manipulates lava and molten rock',
        'Preferred Environment': 'Volcanic caverns and lava flows',
        'Dragon Type': 'Wyrms',
        'Best Suited For': 'Fire magic and embracing the heat',
        'Social vs Solitary': 'Solitary, often found in volcanic realms',
        'Ideal Owner': 'Fire mages, lava explorers, and passionate individuals',
        'Lifespan': '250-300 years',
        'Mass': '800 lbs',
        'Scientific Name': 'Pyrodraco Ignis',
        'Breeding Sanctuary': 'Dragagon Drakes',
        'Availability': 'Common',
    },
    
    {
        'Name': 'Mossback Wyrms',
        'Common Colors': 'Mossy greens, earthy browns, and weathered grays',
        'Egg Colors': 'Adorned with moss-like patterns and hues',
        'Temperament': 'Ancient and wise',
        'Beginner Friendly': 'No',
        'Size': 'Large',
        'Special Abilities': 'Enhances earth magic and communicates with nature',
        'Preferred Environment': 'Ancient forests and misty groves',
        'Dragon Type': 'Wyrms',
        'Best Suited For': 'Nature magic and embodying ancient wisdom',
        'Social vs Solitary': 'Solitary, often seen in serene forest clearings',
        'Ideal Owner': 'Druids, mystics, and seekers of ancient knowledge',
        'Lifespan': '300-350 years',
        'Mass': '700 lbs',
        'Scientific Name': 'Muscoscama Antiquus',
        'Breeding Sanctuary': 'Veridinia Hatchery',
        'Availability': 'Common',

    },
    
    {
        'Name': 'Luminoscale Wyrms',
        'Common Colors': 'Radiant whites, shimmering silvers, and celestial blues',
        'Egg Colors': 'Gleaming with inner starlight',
        'Temperament': 'Ethereal and otherworldly',
        'Beginner Friendly': 'No',
        'Size': 'Large',
        'Special Abilities': 'Manipulates light and creates celestial displays',
        'Preferred Environment': 'Astral planes and open night skies',
        'Dragon Type': 'Wyrms',
        'Best Suited For': 'Light magic and connecting with the cosmos',
        'Social vs Solitary': 'Solitary, often found stargazing',
        'Ideal Owner': 'Astral travelers, light mages, and dreamweavers',
        'Lifespan': '400-450 years',
        'Mass': '800 lbs',
        'Scientific Name': 'Lucidodracon Aetherius',
        'Breeding Sanctuary': 'Mystique Magesparks',
        'Availability': 'Limited',
    },
    
    {
        'Name': 'Umbravale Wyrms',
        'Common Colors': 'Deep blacks, shadowy grays, and smoky purples',
        'Egg Colors': 'Gleaming with inner darkness and mystery',
        'Temperament': 'Enigmatic and contemplative',
        'Beginner Friendly': 'No',
        'Size': 'Large',
        'Special Abilities': 'Manipulates shadows and delves into the unknown',
        'Preferred Environment': 'Shadowy valleys and hidden realms',
        'Dragon Type': 'Wyrms',
        'Best Suited For': 'Shadow magic and exploring hidden truths',
        'Social vs Solitary': 'Solitary, often seeks solitude for meditation',
        'Ideal Owner': 'Shadowmancers, truth-seekers, and mystics',
        'Lifespan': '300-350 years',
        'Mass': '700 lbs',
        'Scientific Name': 'Umbradracon Arcanus',
        'Breeding Sanctuary': 'Mystique Magesparks',
        'Availability': 'Limited',
    },
    
    {
        'Name': 'Cinderflow Wyrms',
        'Common Colors': 'Fiery reds, molten oranges, and glowing yellows',
        'Egg Colors': 'Gleaming with inner volcanic heat',
        'Temperament': 'Intense and passionate',
        'Beginner Friendly': 'No',
        'Size': 'Large',
        'Special Abilities': 'Manipulates lava and molten rock, embodies passion',
        'Preferred Environment': 'Volcanic landscapes and fiery chasms',
        'Dragon Type': 'Wyrms',
        'Best Suited For': 'Fire magic and embracing inner fervor',
        'Social vs Solitary': 'Solitary, often found near volcanic vents',
        'Ideal Owner': 'Fire mages, lava enthusiasts, and passionate souls',
        'Lifespan': '250-300 years',
        'Mass': '800 lbs',
        'Scientific Name': 'Pyrodraco Ardor',
        'Breeding Sanctuary': 'Dragagon Drakes',
        'Availability': 'Uncommon',
    },
    
    {
        'Name': 'Nebulight Wyrms',
        'Common Colors': 'Cosmic purples, deep blues, and iridescent whites',
        'Egg Colors': 'Glowing with interstellar energy',
        'Temperament': 'Mystical and transcendent',
        'Beginner Friendly': 'No',
        'Size': 'Large',
        'Special Abilities': 'Manipulates cosmic energies and cosmic connections',
        'Preferred Environment': 'Celestial observatories and astral realms',
        'Dragon Type': 'Wyrms',
        'Best Suited For': 'Celestial magic and connecting with the universe',
        'Social vs Solitary': 'Solitary, often meditating under the stars',
        'Ideal Owner': 'Astrologers, cosmic mages, and seekers of higher knowledge',
        'Lifespan': '400-450 years',
        'Mass': '800 lbs',
        'Scientific Name': 'Nebulodracon Ethereus',
        'Breeding Sanctuary': 'Mystique Magesparks',
        'Availability': 'Limited',
    },
    
    {
        'Name': 'Verdevine Wyrms',
        'Common Colors': 'Earthy greens, rich browns, and verdant golds',
        'Egg Colors': 'Adorned with patterns reminiscent of lush landscapes',
        'Temperament': 'Nurturing and grounded',
        'Beginner Friendly': 'Yes',
        'Size': 'Large',
        'Special Abilities': 'Communicates with nature and enhances earth magic',
        'Preferred Environment': 'Enchanted forests and vibrant gardens',
        'Dragon Type': 'Wyrms',
        'Best Suited For': 'Nature magic and cultivating harmony',
        'Social vs Solitary': 'Solitary, often found among ancient trees',
        'Ideal Owner': 'Druids, gardeners, and nature-loving souls',
        'Lifespan': '300-350 years',
        'Mass': '700 lbs',
        'Scientific Name': 'Viridodracon Vitalis',
        'Breeding Sanctuary': 'Veridinia Hatchery',
        'Availability': 'Common'
    },
    
    {
        'Name': 'Magma Leviathans',
        'Common Colors': 'Molten reds, fiery oranges, and glowing yellows',
        'Egg Colors': 'Incandescent and pulsating with heat',
        'Temperament': 'Dominant and fiercely territorial',
        'Beginner Friendly': 'No',
        'Size': 'Enormous',
        'Special Abilities': 'Controls magma flows and volcanic eruptions',
        'Preferred Environment': 'Active volcanoes and lava-filled caverns',
        'Dragon Type': 'Leviathans',
        'Best Suited For': 'Lava manipulation and volcano guardianship',
        'Social vs Solitary': 'Solitary, rarely tolerates others',
        'Ideal Owner': 'Expert geologists and fire mages',
        'Lifespan': '400-450 years',
        'Mass': '2500 lbs',
        'Scientific Name': 'Pyromegaleviathan Ignius',
        'Breeding Sanctuary': 'Ingniss Guardians',
        'Availability': 'Limited',
    },
    
    {
        'Name': 'Glaciermaw Leviathans',
        'Common Colors': 'Icy blues, frosty whites, and hints of silver',
        'Egg Colors': 'Gleaming like ice under the moonlight',
        'Temperament': 'Majestic and commanding',
        'Beginner Friendly': 'No',
        'Size': 'Enormous',
        'Special Abilities': 'Controls ice and freezing winds',
        'Preferred Environment': 'Glacial valleys and frozen fjords',
        'Dragon Type': 'Leviathans',
        'Best Suited For': 'Glacial magic and polar guardianship',
        'Social vs Solitary': 'Solitary, prefers the frozen isolation',
        'Ideal Owner': 'Polar explorers and ice mages',
        'Lifespan': '400-450 years',
        'Mass': '2500 lbs',
        'Scientific Name': 'Gelusmegalos Glacies',
        'Breeding Sanctuary': 'Ingniss Guardians',
        'Availability': 'Seasonal',
    },
    
    {
        'Name': 'Abyssal Leviathans',
        'Common Colors': 'Inky blacks, dark purples, and iridescent blues',
        'Egg Colors': 'Glowing with deep-sea luminescence',
        'Temperament': 'Enigmatic and mysterious',
        'Beginner Friendly': 'No',
        'Size': 'Enormous',
        'Special Abilities': 'Controls darkness and deep-sea currents',
        'Preferred Environment': 'Abyssal depths and hidden trenches',
        'Dragon Type': 'Leviathans',
        'Best Suited For': 'Dark magic and exploring the depths',
        'Social vs Solitary': 'Solitary, rarely encounters other creatures',
        'Ideal Owner': 'Deep-sea explorers and shadow mages',
        'Lifespan': '400-450 years',
        'Mass': '2500 lbs',
        'Scientific Name': 'Abyssamegalos Obscurus',
        'Breeding Sanctuary': 'Ingniss Guardians',
        'Availability': 'Seasonal',
    },
    
    {
        'Name': 'Tidesurge Sea Serpents',
        'Common Colors': 'Ocean blues, shimmering silvers, and pearlescent whites',
        'Egg Colors': 'Glowing with inner aquatic radiance',
        'Temperament': 'Dynamic and spirited',
        'Beginner Friendly': 'No',
        'Size': 'Enormous',
        'Special Abilities': 'Controls tidal waves and aquatic currents',
        'Preferred Environment': 'Deep oceans and turbulent waters',
        'Dragon Type': 'Sea serpents',
        'Best Suited For': 'Oceanic exploration and water manipulation',
        'Social vs Solitary': 'Social, forms bonds with other sea creatures',
        'Ideal Owner': 'Marine biologists and aquatic mages',
        'Lifespan': '300-350 years',
        'Mass': '2000 lbs',
        'Scientific Name': 'Aequora Serpentus',
        'Breeding Sanctuary': 'Ingniss Guardians',
        'Availability': 'Rare',
    },
    
    {
        'Name': 'Crystalfin Sea Serpents',
        'Common Colors': 'Prismatic blues, iridescent greens, and shimmering silvers',
        'Egg Colors': 'Glowing with aquatic light and colors',
        'Temperament': 'Mystical and enchanting',
        'Beginner Friendly': 'No',
        'Size': 'Enormous',
        'Special Abilities': 'Manipulates ocean currents and sea magic',
        'Preferred Environment': 'Coral reefs and underwater caves',
        'Dragon Type': 'Sea serpents',
        'Best Suited For': 'Oceanic magic and underwater exploration',
        'Social vs Solitary': 'Solitary, but forms bonds with magical beings',
        'Ideal Owner': 'Oceanic mystics and underwater explorers',
        'Lifespan': '400-450 years',
        'Mass': '2500 lbs',
        'Scientific Name': 'Prisma Serpentis',
        'Breeding Sanctuary': 'Ingniss Guardians',
        'Availability': 'Rare',
    },
    
    {
        'Name': 'Aquaflair Sea Serpents',
        'Common Colors': 'Aquatic blues, greens, and silver scales',
        'Egg Colors': 'Gleaming like sunlit ocean waves',
        'Temperament': 'Calm and serene',
        'Beginner Friendly': 'No',
        'Size': 'Enormous',
        'Special Abilities': 'Controls water currents and storms',
        'Preferred Environment': 'Ocean depths and tranquil waters',
        'Dragon Type': 'Sea serpents',
        'Best Suited For': 'Marine exploration and protection',
        'Social vs Solitary': 'Social, forming bonds with other sea creatures',
        'Ideal Owner': 'Experienced mariners and oceanographers',
        'Lifespan': '400-450 years',
        'Mass': '2000 lbs',
        'Scientific Name': 'Hydroserpentus Calmara',
        'Breeding Sanctuary': 'Ingniss Guardians',
        'Availability': 'Rare',
    },
    
    {
        'Name': 'Skyfire Quetzalcoatl',
        'Common Colors': 'Brilliant reds, oranges, and golds',
        'Egg Colors': 'Gleaming with fiery hues',
        'Temperament': 'Majestic and regal',
        'Beginner Friendly': 'No',
        'Size': 'Large',
        'Special Abilities': 'Controls fire and wind, creating firestorms',
        'Preferred Environment': 'High mountains and open skies',
        'Dragon Type': 'Quetzalcoatls',
        'Best Suited For': 'Skyborne exploration and aerial combat',
        'Social vs Solitary': 'Social, especially in their nesting season',
        'Ideal Owner': 'Experienced dragon enthusiasts and explorers',
        'Lifespan': '300-350 years',
        'Mass': '800 lbs',
        'Scientific Name': 'Pyroscauda Regalis',
        'Breeding Sanctuary': 'Deainuis Dragonry',
        'Availability': 'Protected',
    },
    
    {
        'Name': 'Aurorapulse Quetzalcoatls',
        'Common Colors': 'Vibrant purples, deep blues, and radiant oranges',
        'Egg Colors': 'Gleaming with auroral lights and energy',
        'Temperament': 'Energetic and dynamic',
        'Beginner Friendly': 'No',
        'Size': 'Large',
        'Special Abilities': 'Manipulates light and displays auroras',
        'Preferred Environment': 'Polar skies and regions with strong magnetic fields',
        'Dragon Type': 'Quetzalcoatls',
        'Best Suited For': 'Light manipulation and creating colorful displays',
        'Social vs Solitary': 'Social, often seen flying in formation',
        'Ideal Owner': 'Aurora chasers, sky artists, and light mages',
        'Lifespan': '200-250 years',
        'Mass': '1800 lbs',
        'Scientific Name': 'Auroracoatl Lumina',
        'Breeding Sanctuary': 'Deainuis Dragonry',
        'Availability': 'Protected',
    },

    {
        'Name': 'Zephyrflare Quetzalcoatls',
        'Common Colors': 'Radiant golds, fiery oranges, and gentle yellows',
        'Egg Colors': 'Gleaming with warm breezy hues',
        'Temperament': 'Calm and uplifting',
        'Beginner Friendly': 'Yes',
        'Size': 'Large',
        'Special Abilities': 'Manipulates gentle winds and radiates warmth',
        'Preferred Environment': 'Sunny valleys and open skies',
        'Dragon Type': 'Quetzalcoatls',
        'Best Suited For': 'Air manipulation and bringing sunshine',
        'Social vs Solitary': 'Social, often seen during fair weather',
        'Ideal Owner': 'Wind mages, weather enthusiasts, and sun seekers',
        'Lifespan': '180-220 years',
        'Mass': '1600 lbs',
        'Scientific Name': 'Zephyracoatl Radiatus',
        'Breeding Sanctuary': 'Deainuis Dragonry',
        'Availability': 'Protected',
    },
    
    {
        'Name': 'Iridescent Quetzalcoatls',
        'Common Colors': 'Shimmering purples, opalescent blues, and luminous greens',
        'Egg Colors': 'Gleaming with multi-colored iridescence',
        'Temperament': 'Mystical and enchanting',
        'Beginner Friendly': 'No',
        'Size': 'Large',
        'Special Abilities': 'Manipulates light and emits captivating hues',
        'Preferred Environment': 'Rainbow-lit skies and enchanted clouds',
        'Dragon Type': 'Quetzalcoatls',
        'Best Suited For': 'Light magic and creating dazzling displays',
        'Social vs Solitary': 'Social, often seen during celestial events',
        'Ideal Owner': 'Illusionists, light mages, and dreamweavers',
        'Lifespan': '250-300 years',
        'Mass': '1800 lbs',
        'Scientific Name': 'Iridacoatl Lumina',
        'Breeding Sanctuary': 'Deainuis Dragonry',
        'Availability': 'Protected',
    },
    
    {
        'Name': 'Nimbus Quetzalcoatls',
        'Common Colors': 'Ethereal whites, soft blues, and silver accents',
        'Egg Colors': 'Gleaming with cloud-like wisps and hues',
        'Temperament': 'Serene and contemplative',
        'Beginner Friendly': 'Yes',
        'Size': 'Large',
        'Special Abilities': 'Manipulates mist and brings calming rains',
        'Preferred Environment': 'Misty valleys and tranquil lakes',
        'Dragon Type': 'Quetzalcoatls',
        'Best Suited For': 'Rain manipulation and invoking tranquility',
        'Social vs Solitary': 'Solitary, often seen above misty landscapes',
        'Ideal Owner': 'Rain mages, meditators, and cloud enthusiasts',
        'Lifespan': '200-250 years',
        'Mass': '1700 lbs',
        'Scientific Name': 'Nimbuscoatl Serenus',
        'Breeding Sanctuary': 'Deainuis Dragonry',
        'Availability': 'Protected',
    },
    
    {
        'Name': 'Sylvanbark Landwyrms',
        'Scientific name': 'Sylvanodracon Antiquus',
        'Dragon species': 'Landwyrms',
        'Commmon colour(s)': 'Earthy greens, rich browns, and mossy accents',
        'Egg colour(s)': 'Gleaming with patterns reminiscent of ancient forests',
        'Mass': '3200 lbs',
        'Size': 'Enormous',
        'Lifespan': '400-450 years',
        'Special Abilities': 'Communicates with nature and enhances earth magic',
        'Temperament': 'Nurturing and wise',
        'Social (or solitary)': 'Solitary, often found deep within forests',
        'Preferred environment': 'Ancient woods and sacred groves',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Druids, mystics, and those who seek connection',
        'Best suited for': 'Nature magic and embodying ancient wisdom',
        'Breeding sanctuary': 'Veridinia Hatchery',
        'Availability': 'Seasonal',
    },
    
    {
        'Name': 'Celestialspark Landwyrms',
        'Scientific name': 'Astravermis Radiatus',
        'Dragon species': 'Landwyrms',
        'Commmon colour(s)': 'Radiant golds, shimmering blues, and cosmic accents',
        'Egg colour(s)': 'Gleaming with celestial patterns and energy',
        'Mass': '2800 lbs',
        'Size': 'Enormous',
        'Lifespan': '400-450 years',
        'Special Abilities': 'Manipulates cosmic energies and emits celestial light',
        'Temperament': 'Ethereal and radiant',
        'Social (or solitary)': 'Solitary, often seen during meteor showers',
        'Preferred environment': 'Astral planes and starlit skies',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Star gazers, astral mages, and those who seek enlightenment',
        'Best suited for': 'Celestial magic and connecting with the cosmos',
        'Breeding sanctuary': 'Celestria Skyscapes',
        'Availability': 'Protected',
    },
    
    {
        'Name': 'Terravine Landwyrms',
        'Scientific name': 'Terravermis Vitalis',
        'Dragon species': 'Landwyrms',
        'Commmon colour(s)': 'Earthy browns, deep greens, and moss-covered textures',
        'Egg colour(s)': 'Gleaming with patterns reminiscent of lush landscapes',
        'Mass': '3400 lbs',
        'Size': 'Enormous',
        'Lifespan': '300-350 years',
        'Special Abilities': 'Enhances earth magic and communicates with plants',
        'Temperament': 'Grounded and nurturing',
        'Social (or solitary)': 'Social, often found among ancient trees',
        'Preferred environment': 'Verdant valleys and ancient forests',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Herbalists, gardeners, and nature enthusiasts',
        'Best suited for': 'Nature magic and cultivating harmony',
        'Breeding sanctuary': 'Veridinia Hatchery',
        'Availability': 'Uncommon',
    },
    
    {
        'Name': 'Embercrust Landwyrms',
        'Scientific name': 'Ignisvermis Ardor',
        'Dragon species': 'Landwyrms',
        'Commmon colour(s)': 'Fiery reds, molten oranges, and charred blacks',
        'Egg colour(s)': 'Gleaming with inner volcanic heat',
        'Mass': '3000 lbs',
        'Size': 'Enormous',
        'Lifespan': '300-350 years',
        'Special Abilities': 'Manipulates lava and controls heat',
        'Temperament': 'Intense and powerful',
        'Social (or solitary)': 'Solitary, often found near active volcanoes',
        'Preferred environment': 'Volcanic calderas and lava fields',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Fire mages, volcano explorers, and those seeking strength',
        'Best suited for': 'Fire manipulation and embracing raw power',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Rare',
    },

    {
        'Name': 'Ironspine Landwyrms',
        'Scientific name': 'Ferrivermis Robustus',
        'Dragon species': 'Landwyrms',
        'Commmon colour(s)': 'Earthy browns, rugged grays, and metallic accents',
        'Egg colour(s)': 'Gleaming with a durable, metallic sheen',
        'Mass': '3200 lbs',
        'Size': 'Enormous',
        'Lifespan': '400-450 years',
        'Special Abilities': 'Enhanced physical resilience and strength',
        'Temperament': 'Resilient and enduring',
        'Social (or solitary)': 'Solitary, often found in rugged terrains',
        'Preferred environment': 'Rocky mountains and deep caverns',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Adventurers, explorers, and those seeking endurance',
        'Best suited for': 'Physical feats and enduring challenges',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Common',
    },
    
    {
        'Name': 'Thornroot Landwyrms',
        'Scientific name': 'Arborivermis Territorialis',
        'Dragon species': 'Landwyrms',
        'Commmon colour(s)': 'Earthy greens, rich browns, and spiky textures',
        'Egg colour(s)': 'Gleaming with patterns reminiscent of natural camouflage',
        'Mass': '2800 lbs',
        'Size': 'Enormous',
        'Lifespan': '250-300 years',
        'Special Abilities': 'Manipulates earth and controls plant growth',
        'Temperament': 'Cautious and territorial',
        'Social (or solitary)': 'Solitary, often found hidden among vegetation',
        'Preferred environment': 'Dense forests and overgrown jungles',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Druids, forest guardians, and defenders of nature',
        'Best suited for': 'Nature magic and defending their territory',
        'Breeding sanctuary': 'Veridinia Hatchery',
        'Availability': 'Seasonal',
    },
    
    {
        'Name': 'Boulderback Landwyrms',
        'Scientific name': 'Petrabacka Durus',
        'Dragon species': 'Landwyrms',
        'Commmon colour(s)': 'Earthy browns, rocky grays, and stone-like textures',
        'Egg colour(s)': 'Gleaming with patterns resembling natural rock formations',
        'Mass': '3000 lbs',
        'Size': 'Enormous',
        'Lifespan': '300-350 years',
        'Special Abilities': 'Enhanced physical strength and earth manipulation',
        'Temperament': 'Stubborn and unyielding',
        'Social (or solitary)': 'Solitary, often found in rugged terrains',
        'Preferred environment': 'Mountainous ranges and rocky plateaus',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Geologists, mountain explorers, and those seeking stability',
        'Best suited for': 'Earth manipulation and enduring challenges',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Common',
    },
    
    {
        'Name': 'Sandshifter Landwyrms',
        'Scientific name': 'Arenavermis Adapta',
        'Dragon species': 'Landwyrms',
        'Commmon colour(s)': 'Sandy browns, desert yellows, and muted tans',
        'Egg colour(s)': 'Gleaming with patterns reminiscent of shifting sands',
        'Mass': '3200 lbs',
        'Size': 'Enormous',
        'Lifespan': '400-450 years',
        'Special Abilities': 'Manipulates sand and controls desert elements',
        'Temperament': 'Adaptable and patient',
        'Social (or solitary)': 'Solitary, often found in desert oases',
        'Preferred environment': 'Arid deserts and sand dunes',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Nomads, desert explorers, and those seeking adaptability',
        'Best suited for': 'Desert survival and sand manipulation',
        'Breeding sanctuary': 'Ingniss Guardians',
        'Availability': 'Limited',
    },
    
    {
        'Name': 'Canyoncarver Landwyrms',
        'Scientific name': 'Ravinivermis Territorialis',
        'Dragon species': 'Landwyrms',
        'Commmon colour(s)': 'Rusty browns, rocky grays, and canyon-like patterns',
        'Egg colour(s)': 'Gleaming with patterns reminiscent of deep canyons',
        'Mass': '2800 lbs',
        'Size': 'Enormous',
        'Lifespan': '250-300 years',
        'Special Abilities': 'Excavates earth and shapes canyons',
        'Temperament': 'Curious and territorial',
        'Social (or solitary)': 'Solitary, often found in secluded canyons',
        'Preferred environment': 'Deep canyons and cliffside habitats',
        'Beginner-friendly': 'No',
        'Ideal owner': 'Geologists, landscape architects, and earth manipulators',
        'Best suited for': 'Earth manipulation and carving landscapes',
        'Breeding sanctuary': 'Veridinia Hatchery',
        'Availability': 'Uncommon',
    },
    
    {
        'Name': 'Mosscrest Landwyrms',
        'Scientific name': 'Sylvanodracon Antiquus',
        'Dragon species': 'Landwyrms',
        'Commmon colour(s)': 'Earthy greens, deep browns, and mossy textures',
        'Egg colour(s)': 'Gleaming with patterns resembling lush forests',
        'Mass': '3400 lbs',
        'Size': 'Enormous',
        'Lifespan': '400-450 years',
        'Special Abilities': 'Communicates with nature and enhances earth magic',
        'Temperament': 'Serene and wise',
        'Social (or solitary)': 'Solitary, often found among ancient trees',
        'Preferred environment': 'Ancient forests and verdant meadows',
        'Beginner-friendly': 'Yes',
        'Ideal owner': 'Druids, nature enthusiasts, and those seeking connection',
        'Best suited for': 'Nature magic and embodying ancient wisdom',
        'Breeding sanctuary': 'Veridinia Hatchery',
        'Availability': 'Seasonal',
    },
    
];

// Trying to implement P24 (methods/structure) into this.
let available = document.getElementById("available");

function createBreeds(i)
{
    let breed = document.createElement('div');
    breed.classList.add("breed");

    let breedInfo = document.createElement('ul');

    for (let info in breeds[i]) 
    {
        if (breeds[i].hasOwnProperty(info)) 
        {
            let infoDetails = document.createElement('li');
            infoDetails.innerText = `${info}: ${breeds[i][info]}`;
            breedInfo.appendChild(infoDetails);
        }
    }

    breed.appendChild(breedInfo);
    available.appendChild(breed);
}

for (i = 0; i < breeds.length; i++)
{
    createBreeds(i);
} 

let showFilter = 'all';

function showSpecies()
{
    available.innerHTML = '';
    
    for (let i = 0; i < breeds.length; i++) 
    {
        if (showFilter === 'all' || breeds[i]['Availability'] === showFilter)
        {
            createBreeds(i);
        }
    }
}

function filterSpecies(species)
{
    showFilter = species;
    showSpecies();
}